// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TabController from "./tab_controller"
application.register("tab", TabController)

import LinkController from "./link_controller"
application.register("link", LinkController)
