// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LinkController from "./link_controller"
application.register("link", LinkController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import TabController from "./tab_controller"
application.register("tab", TabController)
